services:
  db:
    image: postgres:16
    container_name: pos-db
    environment:
      POSTGRES_DB: pos_local
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
