security:
  jwt:
    secret: local-dev-secret-key-for-hs256-minimum-32b

app:
  mail:
    from: no-reply@pos.local

  auth:
    password-reset:
      token-pepper: change-this-local-dev-password-reset-pepper

    email-verification:
      token-pepper: change-this-local-dev-email-verification-pepper

    sms:
      code-pepper: change-this-local-dev-sms-code-pepper
